[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：不支持
;苹果分流：不支持
;增强中国IP段：不支持
;增强国外GFW：不支持


ruleset=节点选择,clash-classic:https://mqjd.github.io/QX/clash/ruleset/OpenAI.yaml
ruleset=REJECT,clash-classic:https://mqjd.github.io/QX/clash/ruleset/Adobe.yaml
ruleset=DIRECT,clash-classic:https://mqjd.github.io/QX/clash/ruleset/Apple.yaml
ruleset=节点选择,clash-classic:https://mqjd.github.io/QX/clash/ruleset/Amazon.yaml
ruleset=DIRECT,clash-classic:https://mqjd.github.io/QX/clash/ruleset/China.yaml
ruleset=InsAndTk,clash-classic:https://mqjd.github.io/QX/clash/ruleset/Facebook.yaml
ruleset=节点选择,clash-classic:https://mqjd.github.io/QX/clash/ruleset/GitHub.yaml
ruleset=节点选择,clash-classic:https://mqjd.github.io/QX/clash/ruleset/Google.yaml
ruleset=DIRECT,clash-classic:https://mqjd.github.io/QX/clash/ruleset/Microsoft.yaml
ruleset=节点选择,clash-classic:https://mqjd.github.io/QX/clash/ruleset/Netflix.yaml
ruleset=节点选择,clash-classic:https://mqjd.github.io/QX/clash/ruleset/NetEase.yaml
ruleset=节点选择,clash-classic:https://mqjd.github.io/QX/clash/ruleset/Spotify.yaml
ruleset=DIRECT,clash-classic:https://mqjd.github.io/QX/clash/ruleset/Steam.yaml
ruleset=节点选择,clash-classic:https://mqjd.github.io/QX/clash/ruleset/Telegram.yaml
ruleset=节点选择,clash-classic:https://mqjd.github.io/QX/clash/ruleset/Twitter.yaml
ruleset=DIRECT,clash-classic:https://mqjd.github.io/QX/clash/ruleset/Tencent.yaml
ruleset=DIRECT,clash-classic:https://mqjd.github.io/QX/clash/ruleset/TencentVideo.yaml
ruleset=节点选择,clash-classic:https://mqjd.github.io/QX/clash/ruleset/YouTube.yaml
ruleset=节点选择,clash-classic:https://mqjd.github.io/QX/clash/ruleset/WhatsApp.yaml
ruleset=DIRECT,clash-classic:https://mqjd.github.io/QX/clash/ruleset/WeChat.yaml
ruleset=节点选择,clash-classic:https://mqjd.github.io/QX/clash/ruleset/PayPal.yaml
ruleset=DIRECT,clash-classic:https://mqjd.github.io/QX/clash/ruleset/Zoom.yaml
ruleset=节点选择,clash-classic:https://mqjd.github.io/QX/clash/ruleset/Proxy.yaml
ruleset=节点选择,clash-classic:https://mqjd.github.io/QX/clash/ruleset/Mine.yaml
ruleset=InsAndTk,https://mqjd.github.io/QX/clash/TikTok.list

ruleset=节点选择,[]DOMAIN-SUFFIX,superwall.me
ruleset=DIRECT,[]DOMAIN-SUFFIX,iphone-ld.apple.com
ruleset=DIRECT,[]DOMAIN-SUFFIX,lcdn-locator.apple.com
ruleset=DIRECT,[]DOMAIN-SUFFIX,lcdn-registration.apple.com
ruleset=DIRECT,[]DOMAIN-SUFFIX,push.apple.com
ruleset=Others,[]MATCH

custom_proxy_group=节点选择`select`[]HK 香港`[]HK Fast`[]TW 台湾`[]SG 新加坡`[]JP 日本`[]US 美国`[]DIRECT
custom_proxy_group=Others`select`[]DIRECT`[]节点选择
custom_proxy_group=InsAndTk`select`[]HK 香港`[]HK Fast`[]TW 台湾`[]SG 新加坡`[]JP 日本`[]US 美国`[]DIRECT
custom_proxy_group=HK 香港`select`(澳门|🇲🇴|港|🇭🇰|HK|(?i)Hong)
custom_proxy_group=HK Fast`select`(澳门|🇲🇴|港|🇭🇰|HK|(?i)Hong).+\d(x|X)
custom_proxy_group=TW 台湾`select`(?=.*(台|TW|Tai))^((?!(免费)).)*$
custom_proxy_group=SG 新加坡`select`(?i)(新加坡|坡|狮城|SG|Singapore)
custom_proxy_group=JP 日本`select`(?i)(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)
custom_proxy_group=US 美国`select`(?i)(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥)

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=rules/ACL4SSR/Clash/GeneralClashConfig.yml                                                                                                                                                            
                                                                                                                                                                                                                       
;luck
